### ISSUE TITLE
How to build python module

### ISSUE THREAD

**Issue by Alexhha** [omniti-labs/jlog#37]
Hello,

could anyone explain how can I build and use jlog in a python script?
```
$ python test_jlog.py
Traceback (most recent call last):
  File "test_jlog.py", line 8, in <module>
    from jlog import *
ImportError: No module named jlog
```

**Comment by leea** [comment]
Hi,

These were my steps for building and using the jlog python module:

from the project root directory:

autoconf
./configure && make && make install
cd python
python setup.py install

**Comment by yqian1991** [comment]
This is what I got following your steps @leea 
```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
```
